spring.application.name=FarmaRedOpsIntelligence

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/farmared_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=${SERVER_PORT:8080}
jwt.secret=${JWT_SECRET:clave_jwt_de_desarrollo_con_minimo_32_caracteres}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

app.documents.storage-path=${DOCUMENT_STORAGE_PATH:uploads/documentos}
app.documents.max-size-bytes=${DOCUMENT_MAX_SIZE_BYTES:10485760}